### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by StackOver1102** [SnoopyCodeX/snoopbot-v2#1]
Error: Cannot find module 'C:\Users\Admin\Desktop\test\test\snoopbot-v2\node_modules\tough-cookie\lib\cookie'. Please verify that the package.json has a valid "main" entry

**Comment by SnoopyCodeX** [comment]
Hi, have you tried reinstalling all the dependencies? Try deleting the `node_modules` folder and execute `npm install` again

**Comment by StackOver1102** [comment]
ERR! listenMqtt Error: Connection refused: Server unavailable

**Comment by SnoopyCodeX** [comment]
> ERR! listenMqtt Error: Connection refused: Server unavailable

Was the previous issue been resolved? I will be closing this issue now. Feel free to open a new issue regarding your new problem.
