### ISSUE TITLE
ERR! listenMqtt Error: Connection refused: Server unavailable

### ISSUE THREAD

**Issue by StackOver1102** [SnoopyCodeX/snoopbot-v2#2]
When I send test message it shows error ERR! listenMqtt Error: Connection refused: Server unavailable

**Comment by SnoopyCodeX** [comment]
Hi good morning, it seems to me that that is a connection issue on your side. If the problem still persists, please provide a more detailed description of the problem. Thank you

**Comment by StackOver1102** [comment]
![image](https://github.com/SnoopyCodeX/snoopbot-v2/assets/60789195/f25fb952-5b59-489e-aa3a-c3da7db2ecbf)

**Comment by StackOver1102** [comment]
I don't know what the cause is

**Comment by StackOver1102** [comment]
ERR! getSeqId { error: 'Not logged in.' }
